### ISSUE TITLE
Can we name this better?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/ember#9]
@gaand asking @jrhorn424 please?

**Comment by gaand** [comment]
@ga-wdi-boston/core:

@jrhorn424 and I discussed, and the unsuffixed name is probably the best options (without further information) for introductory/overview training.  Not least because it sorts well.

**Comment by gaand** [comment]
@jrhorn424 I thought we'd settled this, but since 0014c651b08cfe9f2ee62363ce6ca3465e32f171 uses `ember-overview` everywhere I thought we should chat once more.

The restriction you note in #8, and consistency make me wonder if we should go with the "overview" suffix everywhere.  You can probably talk me out if it :-).

**Comment by jrhorn424** [comment]
Sure, it should be named `ga-wdi-boston.ember` instead. Then it's consistent. 😄

**Comment by gaand** [comment]
Right. Let's do that then. See #8
